# Generated by Django 5.0.2 on 2024-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0003_place_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="image",
            field=models.FilePathField(null=1, path="static/img/cafes"),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name="shop",
            name="image",
            field=models.FilePathField(null=1, path="static/img/shops"),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.FilePathField(null=1, path="static/img/places"),
        ),
    ]
