# Generated by Django 5.0.2 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0004_cafe_image_shop_image_alter_place_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe", name="address", field=models.TextField(default="null"),
        ),
    ]
