# Generated by Django 5.0.2 on 2024-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0006_cafe_type_place_type_shop_type_alter_cafe_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe", name="map_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cafe", name="map_x", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cafe", name="may_y", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="place", name="map_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="place", name="map_x", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="place", name="may_y", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop", name="map_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop", name="map_x", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop", name="may_y", field=models.IntegerField(default=0),
        ),
    ]
