# Generated by Django 5.0.2 on 2024-05-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0007_cafe_map_id_cafe_map_x_cafe_may_y_place_map_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="map_id",),
        migrations.RemoveField(model_name="shop", name="map_x",),
        migrations.RemoveField(model_name="shop", name="may_y",),
    ]
