# Generated by Django 5.0.2 on 2024-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0008_remove_shop_map_id_remove_shop_map_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="redirect_url",
            field=models.TextField(default="cafes"),
        ),
        migrations.AddField(
            model_name="place",
            name="redirect_url",
            field=models.TextField(default="places"),
        ),
    ]
