# Generated by Django 5.0.2 on 2024-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0009_cafe_redirect_url_place_redirect_url"),
    ]

    operations = [
        migrations.RenameField(model_name="cafe", old_name="may_y", new_name="map_y",),
        migrations.RenameField(model_name="place", old_name="may_y", new_name="map_y",),
        migrations.AlterField(
            model_name="cafe",
            name="redirect_url",
            field=models.TextField(default="cafe"),
        ),
    ]
