# Generated by Django 5.0.2 on 2024-05-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0010_rename_may_y_cafe_map_y_rename_may_y_place_map_y_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cafe", name="address",),
        migrations.RemoveField(model_name="shop", name="short_description",),
    ]
