# Generated by Django 5.0.2 on 2024-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0012_userfavourites"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("short_description", models.TextField()),
                ("rating", models.FloatField()),
                ("votes", models.IntegerField()),
                ("creator", models.IntegerField()),
                ("route", models.TextField()),
            ],
        ),
    ]
