# Generated by Django 5.0.2 on 2024-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0013_route"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route", old_name="route", new_name="marshrut",
        ),
    ]
