# Generated by Django 5.0.2 on 2024-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0015_place_geo_x_place_geo_y"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("cost", models.IntegerField()),
                ("image", models.FilePathField(null=1, path="static/img/events")),
                ("place", models.TextField()),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("link", models.TextField()),
            ],
        ),
    ]
