# Generated by Django 5.0.2 on 2024-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0016_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="date", field=models.TextField(),
        ),
    ]
