# Generated by Django 5.0.2 on 2024-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0018_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="type", field=models.IntegerField(default=0),
        ),
    ]
