# Generated by Django 5.0.2 on 2024-05-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0020_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="route",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="belka.route"
            ),
            preserve_default=False,
        ),
    ]
