# Generated by Django 5.0.2 on 2024-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0021_order_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="date", field=models.DateField(),
        ),
    ]
