# Generated by Django 5.0.2 on 2024-05-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0022_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered_user",
            field=models.IntegerField(default=0),
        ),
    ]
