# Generated by Django 5.0.2 on 2024-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belka", "0023_order_ordered_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.TextField(
                default="Заказ на <django.db.models.fields.DateField>"
            ),
        ),
        migrations.AlterField(
            model_name="userfavourites",
            name="favourite_places",
            field=models.TextField(default=""),
        ),
    ]
